#!/usr/bin/env python3
"""Append Philippines v18 energy records to the inherited cumulative ledger."""

from __future__ import annotations

import csv
import hashlib
from pathlib import Path


PACKAGE = Path(__file__).resolve().parents[1]
LEDGER = PACKAGE / "data_sources"
INPUTS = LEDGER / "snapshots" / "energy_inputs_v18_2026-08-12.json"
BUILD = LEDGER / "snapshots" / "energy_inputs_v18_build_manifest.json"
VALIDATION = LEDGER / "snapshots" / "energy_inputs_v18_validation.json"
ARCHIVE_MANIFEST = LEDGER / "V18_MODEL_ARCHIVE_MANIFEST.csv"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def update(filename: str, rows: list[dict[str, str]], supersede: dict[str, str] | None = None) -> None:
    path = LEDGER / filename
    with path.open(newline="", encoding="utf-8-sig") as stream:
        reader = csv.DictReader(stream)
        fields = reader.fieldnames
        existing = list(reader)
    assert fields is not None
    id_field = fields[0]
    incoming = {row[id_field] for row in rows}
    retained = [row for row in existing if row[id_field] not in incoming]
    for row in retained:
        if supersede and row[id_field] in supersede:
            row["superseded_by"] = supersede[row[id_field]]
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        writer.writerows(retained + rows)


def main() -> None:
    for path in (INPUTS, BUILD, VALIDATION, ARCHIVE_MANIFEST):
        if not path.is_file():
            raise FileNotFoundError(path)

    common_hash = sha256(INPUTS)
    sources = [
        ("SRC_BNEF_PHL_PATH_2025", "BloombergNEF", "The Philippines' Path to Clean and Affordable Electricity", "2025-06-03", "2025", "Philippines", "Coal power capital cost", "nominal USD/MW", "Appendix A Table 3; coal 2025 = 1604789 USD/MW", "https://assets.bbhub.io/professional/sites/44/The-Philippines-Path-to-Clean-and-Affordable-Electricity.pdf", "BNEF publication terms", "Philippine country benchmark; source-year dollars retained because the model has no declared price year."),
        ("SRC_NREL_SMR_PROJECTION_2024", "National Renewable Energy Laboratory", "Long-Term Electricity Projections for Kentucky", "NREL/PR-6A40-91633", "2024 reference projection", "United States technology benchmark", "Nuclear SMR capital cost reference path", "USD/kW", "Page 11 nuclear-cost chart; reference near 8000 USD/kW", "https://www.nrel.gov/docs/fy25osti/91633.pdf", "U.S. Government publication", "Used as a transparent central technology benchmark; not a Philippines project quote."),
        ("SRC_IRENA_HYDRO_ROLE_2023", "International Renewable Energy Agency", "The Changing Role of Hydropower", "2023", "fleet outlook", "Global", "Hydropower plant and component lives", "years", "Page 28 Table 3 and footnote 4; average plant life 60 years", "https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2023/Feb/IRENA_Changing_role_of_hydropower_2023.pdf", "IRENA publication terms", "Supports 60 years as an interim whole-plant life rather than the inherited 100 years."),
        ("SRC_PHL_DOE_NG_STATS_2023", "Philippine Department of Energy", "Natural Gas Production and Consumption", "as of 2023-08-15", "2020-2022", "Philippines", "Domestic natural-gas production", "mmscf", "Annual production: 141732; 121089; 113611 mmscf", "https://legacy.doe.gov.ph/natgas/natural-gas-production-and-consumption-august-15-2023", "Philippine government publication", "Historical domestic-route ceilings."),
        ("SRC_PHL_DOE_GAS_REPORT_2023", "Philippine Department of Energy", "OIMB Year-end Comprehensive Report FY 2023", "FY2023", "2023", "Philippines", "Malampaya production; LNG entry and imported-gas use", "mmscf; date", "Section 3.2; LNG commenced April 2023; domestic production 89215 mmscf; imported demand 21311 mmscf", "https://legacy.doe.gov.ph/sites/default/files/pdf/downstream_oil/year-end-comprehensive-report-FY2023.pdf", "Philippine government publication", "Establishes the import chronology and 2023 partial-year ceiling."),
        ("SRC_PHL_DOE_GAS_PROD_2024", "Philippine Department of Energy", "Petroleum Production 2024", "2024", "2024", "Philippines", "Malampaya natural-gas production", "mmscf", "Annual total 70337.85 mmscf", "https://prod-cms.doe.gov.ph/documents/d/erdb/petroleum-production-2024-pdf", "Philippine government publication", "Latest observed domestic production used in the installed path."),
        ("SRC_PHL_DOE_LNG_CAPACITY_2024", "Philippine Department of Energy", "Natural-gas transition statement at Norway-Philippines LNG Summit", "2024", "2024 operating outlook", "Philippines", "Combined capacity of two LNG terminals", "MTPA", "Two terminals nearing full commercial operation; combined 8 MTPA", "https://legacy.doe.gov.ph/press-releases/secretary-lotilla-emphasizes-role-natural-gas-energy-transition-at-norway-philippines-lng-summit-2024", "Philippine government publication", "Technical import envelope from 2024; not a demand target."),
        ("SRC_PEZA_MALAMPAYA_PRICE_2020", "Philippine Economic Zone Authority", "Energy bulletin", "2020 context", "2020", "Philippines", "Malampaya gas price", "USD/MMBtu", "Malampaya gas price 7.0289 USD/MMBtu", "https://www.peza.gov.ph/documents/bulletin3energy.pdf", "Philippine government publication", "Anchors the domestic route in 2020."),
        ("SRC_PHL_ERC_LNG_COST_2025", "Philippine Energy Regulatory Commission", "Q1 2025 generation-cost press release", "2025", "Q1 2024 and Q1 2025", "Philippines", "Weighted average landed LNG cost", "USD/MMBtu", "Q1 2024 = 14.9; Q1 2025 = 17.3 USD/MMBtu", "https://www.erc.gov.ph/Press-Singular/84222", "Philippine government publication", "The 2024 value anchors the interim import-price path."),
        ("SRC_IEEFA_LNG_OUTLOOK_2024", "Institute for Energy Economics and Financial Analysis", "Global LNG Outlook 2024-2028", "2024", "April 2023-February 2024", "Philippines", "Average imported LNG price", "USD/MMBtu", "Philippines average 13.91 USD/MMBtu", "https://ieefa.org/sites/default/files/2024-04/Global%20LNG%20Outlook%202024-2028_April%202024%20%28Final%29.pdf", "IEEFA publication terms", "Secondary synthesis used only for the 2023 import-route anchor."),
        ("SRC_EIA_ENERGY_CONVERSIONS_2026", "U.S. Energy Information Administration", "Energy conversion calculators and AFDC LNG fuel properties", "2026 access", "conversion factors", "General", "Natural gas and LNG heat content", "Btu/scf; Btu/lb", "1036 Btu/scf natural gas; 21240 Btu/lb LNG", "https://www.eia.gov/energyexplained/units-and-calculators/energy-conversion-calculators.php", "U.S. Government publication", "Unit conversion only; heat content varies by supply."),
        ("SRC_PHL_PR1_ENERGY_DIAGNOSTIC", "EAPD-DRB contributor", "CLEWs-PHL pull request 1 energy decision register", "head 721f5470e3ccd9e7237622c3270e68eae60a2faa", "diagnostic through 2026-08-06", "Philippines", "Energy input findings including coal conversion check", "diagnostic record", "LAND_WATER_CALIBRATION_DECISIONS.md section 6", "https://github.com/EAPD-DRB/CLEWs-PHL/pull/1", "Repository terms", "Used as diagnostic evidence; v18 independently records accepted values and limitations."),
        ("SRC_PHL_V18_ENERGY_INPUTS", "EAPD-DRB", "Philippines v18 normalized energy-input record", "2026-08-12", "2020-2053", "Philippines", "All values formulas IDs source URLs and limitations", "record", "snapshots/energy_inputs_v18_2026-08-12.json", "", "Repository terms; underlying sources retain provider terms", "Standalone normalized source record."),
        ("SRC_PHL_V18_ENERGY_BUILD", "EAPD-DRB", "Philippines v18 energy build manifest", "2026-08-12", "2020-2053", "Philippines", "Source hashes and exact changed files", "record", "snapshots/energy_inputs_v18_build_manifest.json", "", "Repository terms", "Generated from the committed v17 source."),
        ("SRC_PHL_V18_ENERGY_VALIDATION", "EAPD-DRB", "Philippines v18 full-chain validation", "2026-08-12", "2020-2053", "Philippines", "Solver status parameter checks gas limits and land regressions", "record", "snapshots/energy_inputs_v18_validation.json", "", "Repository terms", "Canonical BASE solve and source validation."),
        ("SRC_PHL_V18_MODEL_ARCHIVE", "EAPD-DRB", "Philippines v18 result-free portable MUIO case", "v18.0.0", "2020-2053", "Philippines", "Archive hash size member count and exclusions", "record", "V18_MODEL_ARCHIVE_MANIFEST.csv", "", "Repository terms", "Complete editable case; runtime results excluded."),
    ]
    source_rows = []
    local_hashes = {
        "SRC_PHL_V18_ENERGY_INPUTS": (sha256(INPUTS), "snapshots/energy_inputs_v18_2026-08-12.json"),
        "SRC_PHL_V18_ENERGY_BUILD": (sha256(BUILD), "snapshots/energy_inputs_v18_build_manifest.json"),
        "SRC_PHL_V18_ENERGY_VALIDATION": (sha256(VALIDATION), "snapshots/energy_inputs_v18_validation.json"),
        "SRC_PHL_V18_MODEL_ARCHIVE": (sha256(ARCHIVE_MANIFEST), "V18_MODEL_ARCHIVE_MANIFEST.csv"),
    }
    for sid, provider, product, edition, period, geo, variable, unit, locator, url, license_text, notes in sources:
        digest, local = local_hashes.get(sid, (common_hash, "snapshots/energy_inputs_v18_2026-08-12.json"))
        source_rows.append({"source_id": sid, "provider": provider, "product": product, "edition": edition, "reference_period": period, "geography": geo, "variable": variable, "source_unit": unit, "exact_locator": locator, "url": url, "access_date": "2026-08-12", "license": license_text, "sha256": digest, "local_file": local, "notes": notes})
    update("SOURCES.csv", source_rows)

    calculations = [
        {"calculation_id":"CALC_PHL_V18_ONSHORE_CF","formula":"184.4 TWh / (95.8 GW * 8.76 TWh/GW-year)","source_ids":"SRC_NREL_USAID_SEA_RE_2020","assumption_ids":"","input_calculation_ids":"","input_values":"184.4;95.8;8.76","input_units":"TWh/year;GW;TWh/GW-year","output_value":"0.21973098445200714","output_unit":"fraction","script_path":"scripts/build_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Scales the inherited timeslice profile; the 663.84 PJ/year activity ceiling is unchanged."},
        {"calculation_id":"CALC_PHL_V18_COAL_CV_CHECK","formula":"retain diagnostic DOE benchmark approximately 22.1 GJ/t for any tonne-to-energy conversion","source_ids":"SRC_PHL_PR1_ENERGY_DIAGNOSTIC","assumption_ids":"ASM_PHL_V18_COAL_CV_EVIDENCE_LIMIT","input_calculation_ids":"","input_values":"approximately 22.1","input_units":"GJ/t","output_value":"22.1","output_unit":"GJ/t","script_path":"data_sources/snapshots/energy_inputs_v18_2026-08-12.json","script_version":"v1","notes":"Evidence check only; no coal-price path changes."},
        {"calculation_id":"CALC_PHL_V18_GAS_VOLUME","formula":"PJ = mmscf * 10^6 * 1036 Btu/scf * 1055.05585262 J/Btu / 10^15","source_ids":"SRC_EIA_ENERGY_CONVERSIONS_2026","assumption_ids":"","input_calculation_ids":"","input_values":"1036;1055.05585262","input_units":"Btu/scf;J/Btu","output_value":"0.00109303786331432","output_unit":"PJ/mmscf","script_path":"scripts/build_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Applied to DOE production and use volumes."},
        {"calculation_id":"CALC_PHL_V18_DOMESTIC_CAP","formula":"2020-2024 DOE mmscf * CALC_PHL_V18_GAS_VOLUME; later = 2024 PJ * 0.992^(year-2024)","source_ids":"SRC_PHL_DOE_NG_STATS_2023;SRC_PHL_DOE_GAS_REPORT_2023;SRC_PHL_DOE_GAS_PROD_2024","assumption_ids":"ASM_PHL_V18_DOMESTIC_DECLINE","input_calculation_ids":"CALC_PHL_V18_GAS_VOLUME","input_values":"141732;121089;113611;89215;70337.85;0.992","input_units":"mmscf;fraction/year","output_value":"154.9184;132.3549;124.1811;97.5154;76.8819 then declining","output_unit":"PJ/year","script_path":"scripts/build_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Annual upper limits; not production targets."},
        {"calculation_id":"CALC_PHL_V18_LNG_2023_CAP","formula":"21311 mmscf * CALC_PHL_V18_GAS_VOLUME","source_ids":"SRC_PHL_DOE_GAS_REPORT_2023","assumption_ids":"","input_calculation_ids":"CALC_PHL_V18_GAS_VOLUME","input_values":"21311","input_units":"mmscf","output_value":"23.29372990509147","output_unit":"PJ/year","script_path":"scripts/build_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Observed partial-year import consumption ceiling."},
        {"calculation_id":"CALC_PHL_V18_LNG_TERMINAL_CAP","formula":"8 MTPA * 10^6 t/Mt * 21240 Btu/lb * 2.20462262185 lb/kg * 1055.05585262 J/Btu","source_ids":"SRC_PHL_DOE_LNG_CAPACITY_2024;SRC_EIA_ENERGY_CONVERSIONS_2026","assumption_ids":"ASM_PHL_V18_LNG_TERMINAL_ENVELOPE","input_calculation_ids":"","input_values":"8;21240","input_units":"MTPA;Btu/lb","output_value":"395.2339200002194","output_unit":"PJ/year","script_path":"scripts/build_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Technical ceiling from 2024; not a demand target."},
        {"calculation_id":"CALC_PHL_V18_MALAMPAYA_PRICE","formula":"7.0289 USD/MMBtu / 1.05505585262 GJ/MMBtu","source_ids":"SRC_PEZA_MALAMPAYA_PRICE_2020;SRC_EIA_ENERGY_CONVERSIONS_2026","assumption_ids":"ASM_PHL_V18_COST_CONVENTION","input_calculation_ids":"","input_values":"7.0289;1.05505585262","input_units":"USD/MMBtu;GJ/MMBtu","output_value":"6.662111756970275","output_unit":"MUSD/PJ","script_path":"scripts/build_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Inherited domestic-price shape scaled to this 2020 anchor."},
        {"calculation_id":"CALC_PHL_V18_LNG_PRICE","formula":"USD/MMBtu / 1.05505585262 GJ/MMBtu","source_ids":"SRC_IEEFA_LNG_OUTLOOK_2024;SRC_PHL_ERC_LNG_COST_2025;SRC_EIA_ENERGY_CONVERSIONS_2026","assumption_ids":"ASM_PHL_V18_COST_CONVENTION","input_calculation_ids":"","input_values":"13.91;14.9;1.05505585262","input_units":"USD/MMBtu;USD/MMBtu;GJ/MMBtu","output_value":"13.184136143558241 in 2023;14.122475092668427 in 2024","output_unit":"MUSD/PJ","script_path":"scripts/build_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Inherited import-price shape scaled from the 2024 anchor."},
        {"calculation_id":"CALC_PHL_V18_OBJECTIVE_CHANGE","formula":"(v18 objective - v17 objective) / v17 objective * 100","source_ids":"SRC_PHL_V18_ENERGY_VALIDATION;SRC_PHL_V17_LAND_VALIDATION","assumption_ids":"","input_calculation_ids":"","input_values":"369743557.68076980;369740345.77061987","input_units":"model cost;model cost","output_value":"0.0008686934457308366","output_unit":"percent","script_path":"scripts/validate_philippines_v18_energy_inputs.py","script_version":"v1","notes":"Both canonical BASE runs solved optimally."},
    ]
    update("CALCULATIONS.csv", calculations)

    assumptions = [
        {"assumption_id":"ASM_PHL_V18_GEOTHERMAL_CEILING","statement":"Use 0.70 as the interim central geothermal annual availability ceiling.","central_value":"0.70","unit":"fraction","evidence_source_ids":"SRC_PHL_V16_ENERGY_INPUT_MANIFEST","lower_bound":"0.637","upper_bound":"0.700","rationale":"The v16 installed and dependable benchmarks support a physical ceiling well below 0.90 while 0.70 avoids fitting utilization as a target.","notes":"Replace with plant-level outage and steam-field availability data."},
        {"assumption_id":"ASM_PHL_V18_COST_CONVENTION","statement":"Use source-year USD values directly because the inherited model declares no common price year.","central_value":"source-year dollars","unit":"USD","evidence_source_ids":"SRC_BNEF_PHL_PATH_2025;SRC_NREL_SMR_PROJECTION_2024;SRC_PEZA_MALAMPAYA_PRICE_2020;SRC_PHL_ERC_LNG_COST_2025","lower_bound":"","upper_bound":"","rationale":"This is more transparent than falsely labelling mixed-year evidence as constant 2020 USD.","notes":"A common real price year remains a high-priority gap."},
        {"assumption_id":"ASM_PHL_V18_CAPEX_PATH","statement":"Hold the selected coal and SMR capital-cost benchmarks flat through 2053.","central_value":"1604.789 coal;8000 SMR","unit":"MUSD/GW","evidence_source_ids":"SRC_BNEF_PHL_PATH_2025;SRC_NREL_SMR_PROJECTION_2024","lower_bound":"","upper_bound":"","rationale":"Installs central evidence without adding an unsupported learning or escalation forecast.","notes":"Source reference years differ and are explicit."},
        {"assumption_id":"ASM_PHL_V18_DOMESTIC_DECLINE","statement":"After observed 2024 production apply a 0.8 percent annual decline to the domestic-route ceiling.","central_value":"0.8","unit":"percent/year","evidence_source_ids":"SRC_PHL_DOE_GAS_PROD_2024","lower_bound":"","upper_bound":"","rationale":"Transparent interim continuation compatible with the DOE PEP decline narrative while retaining possible supplementary domestic fields.","notes":"Not a field-reservoir forecast; update when the Malampaya Phase 4 production profile is public."},
        {"assumption_id":"ASM_PHL_V18_LNG_TERMINAL_ENVELOPE","statement":"Use the DOE-reported combined 8 MTPA operating-terminal capacity as the import ceiling from 2024.","central_value":"8","unit":"MTPA","evidence_source_ids":"SRC_PHL_DOE_LNG_CAPACITY_2024","lower_bound":"","upper_bound":"","rationale":"A physical receiving ceiling is preferable to unconstrained import activity and does not force use.","notes":"Does not include later proposed terminals or the PEP 2050 additional-capacity option."},
        {"assumption_id":"ASM_PHL_V18_COAL_CV_EVIDENCE_LIMIT","statement":"Treat approximately 22.1 GJ/t as a conversion check only until the exact DOE table is retained.","central_value":"22.1","unit":"GJ/t","evidence_source_ids":"SRC_PHL_PR1_ENERGY_DIAGNOSTIC","lower_bound":"","upper_bound":"","rationale":"Prevents the 17.6 GJ/t Indonesian-coal proxy from being silently used for Philippine price conversion without overstating evidence precision.","notes":"No v18 coal-price model cell changes."},
    ]
    update("ASSUMPTIONS.csv", assumptions)

    maps = [
        {"map_id":"MAP_PHL_V18_CANONICAL_PACKAGE","model_file":"muio/Philippines_v18_v18.0.0_MUIO.zip","parameter":"complete editable source package","entity":"Philippines_v18","mode":"all","scenario":"all","years":"2020-2053","value_or_expression":"result-free v18.0.0 archive","model_unit":"archive","evidence_ids":"SRC_PHL_V18_MODEL_ARCHIVE;SRC_PHL_V18_ENERGY_BUILD;SRC_PHL_V18_ENERGY_VALIDATION","superseded_by":"","evidence_type":"direct","notes":"Complete cumulative ledger and retained evidence are in this package."},
        {"map_id":"MAP_PHL_V18_GEOTHERMAL_AF","model_file":"case/Philippines_v18/RYT.json","parameter":"AvailabilityFactor","entity":"TEC_0qr3z / PHL_POW_GEO_OLD","mode":"","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"0.70","model_unit":"fraction","evidence_ids":"ASM_PHL_V18_GEOTHERMAL_CEILING;SRC_PHL_V18_ENERGY_INPUTS","superseded_by":"","evidence_type":"estimated","notes":"Supersedes v16 0.90; a ceiling not a generation target."},
        {"map_id":"MAP_PHL_V18_ONSHORE_CF","model_file":"case/Philippines_v18/RYTTs.json","parameter":"CapacityFactor","entity":"TEC_1wdli / PHL_POW_PP_WON","mode":"30 timeslices","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"inherited profile scaled to annual mean 0.21973098445200714","model_unit":"fraction","evidence_ids":"CALC_PHL_V18_ONSHORE_CF;SRC_NREL_USAID_SEA_RE_2020;SRC_PHL_V18_ENERGY_BUILD","superseded_by":"","evidence_type":"derived","notes":"Uses the same restricted screen as the unchanged 663.84 PJ/year activity ceiling."},
        {"map_id":"MAP_PHL_V18_COAL_CC","model_file":"case/Philippines_v18/RYT.json","parameter":"CapitalCost","entity":"TEC_46nha / PHL_POW_PP_COAL","mode":"","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"1604.789","model_unit":"MUSD/GW","evidence_ids":"SRC_BNEF_PHL_PATH_2025;ASM_PHL_V18_COST_CONVENTION;ASM_PHL_V18_CAPEX_PATH","superseded_by":"","evidence_type":"estimated","notes":"Numerically USD/kW; flat source-year benchmark."},
        {"map_id":"MAP_PHL_V18_SMR_CC","model_file":"case/Philippines_v18/RYT.json","parameter":"CapitalCost","entity":"TEC_fa6fe / PHL_POW_PP_NUSMR","mode":"","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"8000","model_unit":"MUSD/GW","evidence_ids":"SRC_NREL_SMR_PROJECTION_2024;ASM_PHL_V18_COST_CONVENTION;ASM_PHL_V18_CAPEX_PATH","superseded_by":"","evidence_type":"estimated","notes":"Central technology benchmark; no Philippine SMR project-cost observation exists."},
        {"map_id":"MAP_PHL_V18_HYDRO_OL","model_file":"case/Philippines_v18/RT.json","parameter":"OperationalLife","entity":"TEC_p3vu5 / PHL_POW_PP_HY_LA","mode":"","scenario":"SC_0","years":"all vintages","value_or_expression":"60","model_unit":"years","evidence_ids":"SRC_IRENA_HYDRO_ROLE_2023;SRC_PHL_V18_ENERGY_INPUTS","superseded_by":"","evidence_type":"direct","notes":"Before 100 years."},
        {"map_id":"MAP_PHL_V18_SMR_OL_CONFIRMED","model_file":"case/Philippines_v18/RT.json","parameter":"OperationalLife","entity":"TEC_fa6fe / PHL_POW_PP_NUSMR","mode":"","scenario":"SC_0","years":"all vintages","value_or_expression":"60","model_unit":"years","evidence_ids":"SRC_NREL_SMR_PROJECTION_2024;SRC_PHL_V18_ENERGY_INPUTS","superseded_by":"","evidence_type":"direct","notes":"Inherited value confirmed and unchanged; the proposed 40-year correction was rejected."},
        {"map_id":"MAP_PHL_V18_GAS_IMPORT_TAU","model_file":"case/Philippines_v18/RYT.json","parameter":"TotalTechnologyAnnualActivityUpperLimit","entity":"TEC_otz0y / PHL_PRO_IMP_NG","mode":"all","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"0 through 2022;23.2937299051 in 2023;395.2339200002 from 2024","model_unit":"PJ/year","evidence_ids":"CALC_PHL_V18_LNG_2023_CAP;CALC_PHL_V18_LNG_TERMINAL_CAP;SRC_PHL_DOE_GAS_REPORT_2023","superseded_by":"","evidence_type":"derived","notes":"Chronology and technical ceilings; no import target."},
        {"map_id":"MAP_PHL_V18_GAS_DOMESTIC_TAU","model_file":"case/Philippines_v18/RYT.json","parameter":"TotalTechnologyAnnualActivityUpperLimit","entity":"TEC_6rwx6 / PHL_PRO_EXTR_NG","mode":"all","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"DOE 2020-2024 production; then 0.8 percent annual decline","model_unit":"PJ/year","evidence_ids":"CALC_PHL_V18_DOMESTIC_CAP;ASM_PHL_V18_DOMESTIC_DECLINE","superseded_by":"","evidence_type":"derived","notes":"Upper envelope not a production target."},
        {"map_id":"MAP_PHL_V18_GAS_IMPORT_VC","model_file":"case/Philippines_v18/RYTM.json","parameter":"VariableCost","entity":"TEC_otz0y / PHL_PRO_IMP_NG","mode":"1","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"pre-2023 inherited but unavailable;13.1841361436 in 2023;2024 inherited shape anchored at 14.1224750927","model_unit":"MUSD/PJ","evidence_ids":"CALC_PHL_V18_LNG_PRICE;SRC_PHL_V18_ENERGY_INPUTS","superseded_by":"","evidence_type":"derived","notes":"Existing import route; no new commodity or technology."},
        {"map_id":"MAP_PHL_V18_GAS_DOMESTIC_VC","model_file":"case/Philippines_v18/RYTM.json","parameter":"VariableCost","entity":"TEC_6rwx6 / PHL_PRO_EXTR_NG","mode":"1","scenario":"SC_0; policy rows inherit","years":"2020-2053","value_or_expression":"inherited shape scaled to 6.66211175697 in 2020","model_unit":"MUSD/PJ","evidence_ids":"CALC_PHL_V18_MALAMPAYA_PRICE;SRC_PHL_V18_ENERGY_INPUTS","superseded_by":"","evidence_type":"derived","notes":"Existing domestic route."},
        {"map_id":"MAP_PHL_V18_COAL_CV_CHECK","model_file":"case/Philippines_v18/RYTM.json","parameter":"VariableCost conversion review","entity":"TEC_khtrp / PHL_PRO_IMP_COAL","mode":"1","scenario":"SC_0","years":"2020-2053","value_or_expression":"approximately 22.1 GJ/t conversion benchmark; model price path unchanged","model_unit":"GJ/t","evidence_ids":"CALC_PHL_V18_COAL_CV_CHECK;ASM_PHL_V18_COAL_CV_EVIDENCE_LIMIT","superseded_by":"","evidence_type":"derived","notes":"Evidence-only review mapping; not a changed model cell."},
        {"map_id":"MAP_PHL_V18_VALIDATION","model_file":"case/Philippines_v18/res/ENERGY_INPUTS_V18_BASE","parameter":"full-chain validation","entity":"Philippines_v18","mode":"all","scenario":"BASE","years":"2020-2053","value_or_expression":"Optimal objective 369743557.68076980; all v18 checks pass","model_unit":"validation record","evidence_ids":"SRC_PHL_V18_ENERGY_VALIDATION","superseded_by":"","evidence_type":"direct","notes":"Runtime results excluded from archive; retained normalized validation is included."},
    ]
    update("MODEL_MAP.csv", maps, {"MAP_PHL_V16_GEOTHERMAL_AF": "CHG_PHL_V18_ENERGY_INPUTS_20260812"})

    gaps = [
        {"item":"Common energy-cost price year","why_absent":"The inherited model declares USD and cost units but no real or nominal price year; v18 sources span 2020-2025.","upgrade_source":"Adopt and document one model-wide real price year then rebase every capital fixed and variable cost with a retained deflator series.","priority":"high","notes":"V18 uses source-year dollars directly and labels each reference year rather than claiming false constant dollars."},
        {"item":"Exact DOE coal calorific-value table byte and locator","why_absent":"PR 1 reports the DOE official value as approximately 22.1 GJ/t but the exact table was not retained or independently located.","upgrade_source":"Retain the exact DOE coal import or energy-balance table with fuel basis and year.","priority":"medium","notes":"V18 records this as a conversion check only and does not change the coal-price path."},
        {"item":"Post-2024 domestic gas production profile","why_absent":"Observed DOE production is available through 2024 but a public annual Malampaya Phase 4 and supplementary-field production profile is not retained.","upgrade_source":"DOE or operator field development plan with annual deliverability and reserve basis.","priority":"high","notes":"V18 uses a transparent 0.8 percent annual decline envelope after 2024."},
        {"item":"Long-term Philippine landed LNG price path","why_absent":"Observed 2023-2025 landed values do not define a defensible 2053 forecast.","upgrade_source":"DOE or ERC long-term landed LNG forecast with shipping regasification contract and real-price basis.","priority":"high","notes":"V18 anchors 2023 and 2024 then preserves the inherited mild path shape."},
        {"item":"Philippine first-of-a-kind SMR project cost","why_absent":"No Philippine SMR has a financed project cost or operating record.","upgrade_source":"Bankable Philippine vendor EPC financing owner cost and contingency study.","priority":"high","notes":"The NREL 8000 USD/kW benchmark is a central technology proxy, not a project quote."},
    ]
    update("GAPS.csv", gaps)

    changes = [{"change_id":"CHG_PHL_V18_ENERGY_INPUTS_20260812","date":"2026-08-12","class":"B","description":"Built v18 from committed v17; retained all land safeguards; installed a 0.70 geothermal ceiling, national restricted-screen onshore CF, Philippine coal capex, central SMR capex, 60-year hydro life, and separate existing domestic/LNG chronology prices and limits.","model_objects":"genData.json; RT.json; RYT.json; RYTM.json; RYTTs.json","evidence_path":"calculation_notes/energy_inputs_v18_2026-08-12.md","map_rows_affected":"MAP_PHL_V16_GEOTHERMAL_AF;MAP_PHL_V18_GEOTHERMAL_AF;MAP_PHL_V18_ONSHORE_CF;MAP_PHL_V18_COAL_CC;MAP_PHL_V18_SMR_CC;MAP_PHL_V18_HYDRO_OL;MAP_PHL_V18_GAS_IMPORT_TAU;MAP_PHL_V18_GAS_DOMESTIC_TAU;MAP_PHL_V18_GAS_IMPORT_VC;MAP_PHL_V18_GAS_DOMESTIC_VC","resolve_status":"resolved","author":"Codex","commit":"","notes":"Canonical BASE solved optimally. No technology commodity global mode user constraint demand activity floor or share was added; v17 land closure was reproduced."}]
    update("CHANGES.csv", changes)
    print("Philippines v18 cumulative ledger updated")


if __name__ == "__main__":
    main()
